name: wired
version: 0.3.3
author: Joris Hermans <hermansj@gmail.com>
description: A modern dependency injection like java spring package
homepage: https://github.com/ForceUniverse/wired
dependencies:
  mirrorme: '>=0.2.2 <0.3.0'
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'
